# Generated by Django 4.2.14 on 2024-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0002_customuser_name_customuser_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('tagline', models.CharField(max_length=5)),
                ('boolean_array', models.JSONField(default=list)),
                ('string_array', models.JSONField(default=list)),
                ('summoner_level', models.IntegerField()),
                ('puuid', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
