# Generated by Django 4.2.14 on 2024-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0003_summoner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='boolean_array',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='puuid',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='string_array',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='summoner_level',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='tagline',
        ),
        migrations.AddField(
            model_name='summoner',
            name='league',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='summoner',
            name='mastery',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='summoner',
            name='matches',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner',
            field=models.JSONField(default=dict),
        ),
    ]
