# Generated by Django 4.2.14 on 2024-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0004_remove_summoner_boolean_array_remove_summoner_puuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='league',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='mastery',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='matches',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
