# Generated by Django 4.2.14 on 2024-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0005_alter_summoner_league_alter_summoner_mastery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.JSONField(default=dict)),
            ],
        ),
    ]
