# Generated by Django 4.2.14 on 2024-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0006_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='matches_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
