# Generated by Django 4.2.14 on 2024-07-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0007_summoner_matches_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
